trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

stages:
- stage: Build
  displayName: "Build Application"
  jobs:
  - job: BuildDotnetApplication    
    steps:
    - task: DotNetCoreCLI@2
      displayName: "Restore Project"
      inputs:
        command: 'restore'
        projects: '**/*.csproj'

    - task: DotNetCoreCLI@2
      displayName: "Test & Code coverage"
      inputs:
        command: test
        projects: '**/*Test.csproj'
        arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    # - task: PublishTestResults@2
    #   displayName: "Publish Test"
    #   inputs:
    #     testRunner: VSTest
    #     testResultsFiles: '**/*.trx'
  
    - task: DotNetCoreCLI@2
      displayName: "Build"
      inputs:
        command: build
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
      
    - task: DotNetCoreCLI@2
      displayName: "Publish"
      inputs:
        command: publish
        publishWebProjects: True
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        zipAfterPublish: True
    
    - task: PublishPipelineArtifact@1
      displayName: "Publish Artifact"
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)' 
        artifactName: 'CurrencyExchange'